name: TEST CI/CD

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: DUMP VAR
        env:
          PATH: ${{vars.PATH}}
        run: |
          echo $PATH
      - run: echo PATH ${{vars.PATH}}
      - run: echo Deploying code to the server
      - run: echo ${{secrets.HOST}} ${{secrets.SSH_USER}}
      - name: accessing the server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASSWORD}}
          script:  |
            cd /home/ubuntu/portfolio-website-solidjs
            git pull
            echo TEST
      